### PR TITLE
fix mingw build

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by xantares** [comment]
7971074 fixes dlls to be installed in PREFIX/bin instead of PREFIX/lib
758cdb5 is the fixed version of #80 
d250022 fixes void* arithmetic
bae8f4e allows to generate the headers when cross-compiling through wine for example

**Comment by meshula** [comment]
these look good to me.

**Comment by meshula** [comment]
@xantares, did you close this because the issues don't occur any more?

**Comment by xantares** [comment]
no, just tired of waiting feedback

**Comment by meshula** [comment]
My feedback is that the changes look good :) I'd suggest leaving the request open until the OpenEXR owners are able to take changes again. Something to bring up at a Siggraph BOF.

**Pull request closed without merging**
