### PR TITLE
Release OpenEXR as NuGet

### PR DESCRIPTION
**Pull request by mancoast**
These scripts compile OpenEXR as a NuGet Package.
Use with Visual Studio or MSBuild.
Prepared for continuous integration services.

https://www.nuget.org/packages/openexr-msvc14-x86/
https://www.nuget.org/packages/openexr-msvc14-x64/

### CODE REVIEW

**Comment by mancoast** [comment]
Greetings,

Please provide feedback.

Thanks,
coast

**Comment by meshula** [comment]
Hi @mancoast, What would be the steps to test and verify this patch? I see the nuget.org package links you posted. What is the relationship between this patch, and the nuget.org links you provided? Thanks

**Comment by mancoast** [comment]
Greetings,

This patch includes all the scripts required to generate the binary packages for openexr on nuget.org. To install and test the binary, create a new visual studio project/solution and use the built-in nuget package manager of visual studio to add the openexr nuget.  Now the solution/project has all the headers and lib files required to use the openexr objects and verbs. What are your thoughts regarding the merge of this patch?  It seems the nuget is getting moderate usage based on the statistics available. 

Thanks,
Coast

**Comment by rivaldo4t** [comment]
Hi, I have installed the nugets for OpenExr and Zlib. Now when I `#include <ImfRgbaFile.h>`, it is unable to find the header. Is there something that i am missing here?

**Comment by ghost** [comment]
Greetings,

I made this nuget for the mandelbulber2 project. Please see the usage there. Need response from openexr repo as to wether I should maintain/support. 
Thanks, coast

**Comment by meshula** [comment]
Thanks for the explanations. This patch looks correct. One thing I am wondering about is if it needs to be revised for OpenEXR 2.3? I see this <version>2.2.0.8787</version>, and am also thinking that perhaps the new cmake switches need to be taken into account, (https://github.com/openexr/openexr/blob/master/CMakeLists.txt), although the defaults are probably fine?

**Comment by ghost** [comment]
Greetings Nick,

It is simple to repackage the Nuget with a new revision.  Do you require
the new nuget prior to merge?  Also, with respect to the CMAKE changes,
which new switches require inclusion?  The batch scripts are very flexible
and easy to modify.

Thanks,
coast

**Comment by meshula** [comment]
The 2.2.0.8787 refers to the NuGet version then? I was confused by OpenEXR previously being on version 2.2.

Here are the current external switches, the question is whether they are what the NuGet packaging system needs, or if they need to be overridden.

````
option(OPENEXR_BUILD_ILMBASE        "Build IlmBase"              ON)
option(OPENEXR_BUILD_OPENEXR        "Build OpenEXR"              ON)
option(OPENEXR_BUILD_PYTHON_LIBS    "Build the Python bindings"  ON)
option(OPENEXR_BUILD_VIEWERS        "Build the viewers"          OFF)
option(OPENEXR_BUILD_TESTS          "Enable the tests"           ON)
# when enabled, adds the (long) running fuzz tests to the "make test" rule
# even when this is disabled, as long as OPENEXR_BUILD_TESTS is enabled, one
# can still run "make fuzz" (or equivalent)
option(OPENEXR_RUN_FUZZ_TESTS       "Run damaged-input tests"    OFF)
option(OPENEXR_BUILD_UTILS          "Build the utility programs" ON)

option(OPENEXR_BUILD_SHARED         "Build Shared Libraries"     ON)
option(OPENEXR_BUILD_STATIC         "Build Static Libraries"     OFF)
option(OPENEXR_NAMESPACE_VERSIONING "Use Namespace Versioning"   ON)
option(OPENEXR_FORCE_CXX03          "Force CXX03"                OFF)
set(OPENEXR_PYTHON_MAJOR "2" CACHE STRING "Python major version")
set(OPENEXR_PYTHON_MINOR "7" CACHE STRING "Python minor version")
````

**Comment by ghost** [comment]
Greetings @meshula 

You are correct the 2.2.0.8787 refers to the nuget version.  This version number system expresses the openexr revision and the nuget revision concatenated. The first three numbers are the Semantic Versioning of the openexr software (the latest nuget uses version 2.2.0 of exr and I will update to 2.3 now) and the last number is the nuget version (8787 I will update to 8788).   With respect to the CMAKE switches, I will experiment with specific requirements and add another commit to the PR shortly.

Thanks,
Rob

**Comment by ghost** [comment]
Please see images below for testing/verification
image
image
image
image
image

**Comment by meshula** [comment]
haven't seen the viewer working on Windows for a long time!

**Comment by ghost** [comment]
Hello @meshula

The viewer required an FLTK lib, so I released FLTK on nuget also. With respects to getting this pull request merged Upstream, what else can I do to assist?  I am excited and happy to become a contributor to openexr. 

Thanks,
Rob

**Comment by cary-ilm** [comment]
Hey @mancoast, this all seems to look fine, if you confirm it works, although we've got minimal ability to test it here.  Can you send us a CLA, from http://www.openexr.com/downloads/OpenEXR-Adapted-Contributor-License-Agreement-Individual-2013.doc

Thanks,
- Cary

**Comment by ghost** [comment]
Greetings, CLA sent. Thanks, Rob

**Comment by cary-ilm** [comment]
@mancoast, one more thing - could you add a note to the README.md file explaining the nuget setup? We should at least mention its existence.  Are there any special instructions? Thanks!

**Comment by lgritz** [comment]
In particular, explicitly spelling out the exact Windows command line to use nuget to install the package would be helpful, for those of us who have minimal Windows knowledge but occasionally have to patch Appveyor scripts and the like.

**Comment by cary-ilm** [comment]
merged and rebased  to master.

**Comment by ghost** [comment]
Hello All,

Life has been busy, hence the delayed response. I appreciate the merge and will open a new issue/PR for nuget documentation. 

Thanks,
Rob

**Pull request closed without merging**
